[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=allure-results
markers =
    ui: UI tests
    api: API tests
    smoke: Smoke tests